[package]
name = "groepmaak"
version = "0.1.0"
authors = ["Donatas Rasiukevicius <d.rasiukevicius@labdigital.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.14"
